index:
    path: /
    controller: App\Controller\HomeController::index

usuarios:
    path: /usuarios
    controller: App\Controller\UserController::index

usuario_nuevo:
    path: /usuarios/nuevo
    controller: App\Controller\UserController::new

login:
    path: /login
    controller: App\Controller\SecurityController::login


    
